name: Daily run_update

on:
  # This will run everyday around 08:00 AM
  #schedule:
  #  - cron: "0 13 * * *"
  # Let you run it manually from the Actions tab
  workflow_dispatch:

jobs:
  run-update:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Google credentials file and export path
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: |
          if [ -z "$GOOGLE_APPLICATION_CREDENTIALS_JSON" ]; then
            echo "Missing GOOGLE_APPLICATION_CREDENTIALS_JSON secret" >&2
            exit 1
          fi
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > sa.json
          # Make it available to all subsequent steps (standard pattern)
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/sa.json" >> "$GITHUB_ENV"

      - name: Run updater
        env:
          DOCUSEAL_API_TOKEN: ${{ secrets.DOCUSEAL_API_TOKEN }}
          # also pass through for libraries that respect this var directly
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          if [ -z "$DOCUSEAL_API_TOKEN" ]; then
            echo "Missing DOCUSEAL_API_TOKEN secret" >&2
            exit 1
          fi
          python run_update.py
