name: Run DocuSeal → Google Sheets sync

on:
  schedule:
    # runs 15:00 UTC daily (adjust as you like)
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2 requests

      - name: Run update script
        env:
          DOCUSEAL_API_TOKEN: "FmzWAds1rshavQtaN3BWjSvnHsrW9vuUVLTBMjDuZM4"
          SPREADSHEET_ID: "1cL_1bYaq3Z5wXmOGq8W-t6C6tybyh7MQ-qoxzQfxBKA"
          GOOGLE_APPLICATION_CREDENTIALS: creds.json
          SHEET_NAME: "Sheet1"
          APPEND_RANGE: "A:A"
          START_CELL: "A2"
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: |
          python run_update.py

